
import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { QRCode } from 'qrcode.react';
import { useAuth } from '@/contexts/AuthContext';

const MfaSetup: React.FC = () => {
  const { toast } = useToast();
  const { user } = useAuth();
  const [secret, setSecret] = useState('');
  const [otp, setOtp] = useState('');
  const [mfaEnabled, setMfaEnabled] = useState(false);
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);

  // In a real application, this secret would be generated by the backend
  // and associated with the user's account.
  const generateSecret = () => {
    // This is a placeholder. A real secret would be a base32 encoded string.
    const dummySecret = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    setSecret(dummySecret);
  };

  useEffect(() => {
    generateSecret();
  }, []);

  const handleVerify = () => {
    // In a real application, you would send the OTP to your backend for verification.
    // Here, we'll just simulate a successful verification.
    if (otp.match(/\d{6}/)) {
      setMfaEnabled(true);
      const generatedCodes = Array.from({ length: 10 }, () => Math.random().toString(36).substring(2, 10));
      setRecoveryCodes(generatedCodes);
      toast({ title: "MFA Enabled", description: "MFA has been successfully enabled." });
    } else {
      toast({ title: "Invalid Code", description: "Please enter a valid 6-digit code.", variant: "destructive" });
    }
  };

  if (!user) {
    return null;
  }

  const otpAuthUrl = `otpauth://totp/YourAppName:${user.email}?secret=${secret}&issuer=YourAppName`;

  if (mfaEnabled) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>MFA Enabled</CardTitle>
          <CardDescription>
            Save these recovery codes in a safe place. They can be used to access your account if you lose your device.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-4 bg-gray-100 p-4 rounded-md">
            {recoveryCodes.map((code) => (
              <div key={code} className="font-mono text-sm p-2 bg-white rounded-md shadow-sm">
                {code}
              </div>
            ))}
          </div>
          <Button className="mt-4" onClick={() => navigator.clipboard.writeText(recoveryCodes.join('\n'))}>
            Copy Codes
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Set Up Multi-Factor Authentication</CardTitle>
        <CardDescription>
          Scan the QR code with your authenticator app (e.g., Google Authenticator, Authy).
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col items-center gap-6">
        <div className="p-4 bg-white rounded-lg shadow-md">
          <QRCode value={otpAuthUrl} size={256} />
        </div>
        <p className="text-sm text-gray-600">
          Or enter this code manually: <span className="font-mono bg-gray-100 p-1 rounded">{secret}</span>
        </p>
        <div className="w-full max-w-sm">
          <Label htmlFor="otp">Verification Code</Label>
          <Input
            id="otp"
            type="text"
            value={otp}
            onChange={(e) => setOtp(e.target.value)}
            placeholder="Enter the 6-digit code from your app"
            className="text-center"
          />
        </div>
        <Button onClick={handleVerify} className="w-full max-w-sm">
          Verify and Enable
        </Button>
      </CardContent>
    </Card>
  );
};

export default MfaSetup;
